### PR TITLE
fix: rename 'tasks' folder to 'task'

### PR DESCRIPTION
**Pull request by hervelemeur**
When running `jx pipeline import --url https://github.com/jenkins-x/jx3-pipeline-catalog`

I had this error:

> loading tekton tasks from: https://github.com/jenkins-x/jx3-pipeline-catalog ...

> error: the catalog does not include a 'task' directory at /var/folders/m4/ytp3wjnn1hlbrxt27d64jc3c0000gn/T/jx-git-658269897

Fixes https://github.com/jenkins-x/jx3-pipeline-catalog/issues/70

Signed-off-by: Hervé Le Meur <herve.lemeur@sixense-group.com>

### CODE REVIEW

**Comment by hervelemeur** [comment]
[Slack thread](https://kubernetes.slack.com/archives/C9LTHT2BB/p1607507987143700?thread_ts=1607507795.142200&cid=C9LTHT2BB)

**Comment by jstrachan** [comment]
incidentally we never intended the pipeline catalog to be usable as a tekton catalog; I guess though thats a natural thing for folks to think. The main issue is we didn't want to have to put a version name in the directory; as we're using git sha/branch/tags for versioning

**Comment by hervelemeur** [comment]
replaced by https://github.com/jenkins-x/jx3-pipeline-catalog/pull/331

**Pull request closed without merging**
