### PR TITLE
fix:  compatible more authentication method for docker

### PR DESCRIPTION
**Pull request by wowq**
as https://tekton.dev/docs/pipelines/auth/#configuring-docker-authentication-for-docker
Docker authentication should be used in a more compatible way, rather than using only fixed tokens

### CODE REVIEW

**Comment by babadofar** [comment]
Hi @wowq , did you test this on your end? The Tekton version used by jenkins X is 0.29,  not the latest one

**Comment by wowq** [comment]
I tested it in version 0.29.0 and it worked fine @babadofar

**Review by babadofar — APPROVED** [review]

**Pull request merged**
