### PR TITLE
chore: upgrade kaniko image to 1.9.1

### PR DESCRIPTION
**Pull request by gazal-k**

### CODE REVIEW

**Review by ankitm123 — APPROVED** [review]

**Comment by joshuasimon-taulia** [comment]
after this update, i'm seeing
```
	Showing logs for build my-org/my-app/head #4 stage from-build-pack and container step-build-container-build
time="2022-11-17T01:45:08Z" level=warning msg="Flag --snapshotMode is deprecated. Use: --snapshot-mode"
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "gcr.io/my-org/my-app:0.9.8": creating push check transport for gcr.io failed: GET https://gcr.io/v2/token?scope=repository%3Amy-org%2Fmy-app%3Apush%2Cpull&service=gcr.io: UNAUTHORIZED: Not Authorized.
Pipeline failed on stage 'from-build-pack' : container 'step-build-container-build'. The execution of the pipeline has stopped.
```

**Comment by joshuasimon-taulia** [comment]
nvm, some of my pipelines had custom kaniko steps to push multiple image tags. they were missing https://github.com/jenkins-x/jx3-pipeline-catalog/pull/1194

**Pull request merged**
