### PR TITLE
refactor: upgrade go image to 1.17

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

### CODE REVIEW

**Comment by thevinter** [comment]
Node 17 is not LTS and as such it broke some of my builds. It is not fully compatible yet.

**Comment by ankitm123** [comment]
This test is outdated, uses ancient versions of packages, trying to update and see if it works.

**Comment by ankitm123** [comment]
/override godemo
The tests are very old, and fixing them requires a fix to infra, I think it's safe to merge this, I will keep an eye at the issues after this is merged.

**Pull request merged**
