### PR TITLE
refactor: add pipeline lint step to go plugin multiarch task

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

### CODE REVIEW

**Comment by rawlingsj** [comment]
hmm odd, looks like the BDD test failed with
```
preview jenkins-x-labs-bdd-tests-godemo-pr-16 is now running at https://godemo-pr16.infra.jenkins-x.rocks
--
  |   |   |   | error: failed to update preview : Operation cannot be fulfilled on previews.preview.jenkins.io "jenkins-x-labs-bdd-tests-godemo-pr-16": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by ankitm123** [comment]
Intermittent failure 🤷

**Pull request merged**
