### PR TITLE
fix: use 80 as internal port for th PHP buildpack

### PR DESCRIPTION
**Pull request by hervelemeur**
Fixes https://github.com/jenkins-x/jx3-pipeline-catalog/issues/460

### CODE REVIEW

**Comment by hervelemeur** [comment]
/assign @jstrachan 

Shouldn't the [jenkins-x-buildpacks/jenkins-x-kubernetes](https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes) be archived?
Related to this comment, https://github.com/jenkins-x/jx3-gitops-template/pull/25

**Comment by hervelemeur** [comment]
Shouldn't the \[jenkins-x-buildpacks/jenkins-x-kubernetes\](https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes) be archived?  
Related to this comment, https://github.com/jenkins-x/jx3-gitops-template/pull/25

**Comment by jstrachan** [comment]
@hervelemeur folks still use that repo for jx v2 IIRC

**Pull request merged**
