### PR TITLE
fix: issues with migrated pipelines

### PR DESCRIPTION
**Pull request by Skisocks**
### Fixes:
* GIT_USER -> GIT_NAME in next-version steps
  * Incorrect env var naming for [release-version command](https://github.com/jenkins-x-plugins/jx-release-version/blob/main/main.go#L58)
* Add default GIT_EMAIL env var to next-version steps
  * Tekton git auth initialiser doesn't currently contain an email address so release-version fails (will look at adding this into Tekton but has always been defaulting to the jx email anyway so fine for now)
* Typo in the catalogs pullrequest name
* Reformat the kubetest tasks and add them into the environment pull request pipelineRun
* Set the default workspace size in the packs to 1Gi

### CODE REVIEW

**Comment by msvticket** [comment]
lint-helm doesn't do the same thing as before the first attempt to migration of pipelines. It was running

`            . /workspace/source/.lighthouse/jenkins-x/lint-helm.sh`

but now the standard helm lint is configured to run:

https://github.com/jenkins-x/jx3-pipeline-catalog/blob/master/tasks/helm/pullrequest/build-helm-build.yaml

But for some reason it doesn't run. The lighthousejob is created, but I don't see that it is picked up by the jx-build-controller. I don't see any logs or events related to to the lighthousejob. 🤷 

https://github.com/jenkins-x/jx3-pipeline-catalog/commit/5c43075b80cf48d2ac7d651c59e5510d1920728f

**Comment by msvticket** [comment]
On the other hand: If I checkout the PR and run lint-helm.sh manually it succeeds.

**Comment by msvticket** [comment]
Yeah, I suppose so. But if the pipeline would run it would fail.

**Comment by Skisocks** [comment]
Yeah I'm also not sure why the lint-pipelines PipelineRun hasn't been converted. @tomhobson did you run the command in the root of the catalog? I'll have a look at this

**Comment by Skisocks** [comment]
> Yeah I'm also not sure why the lint-pipelines PipelineRun hasn't been converted. @tomhobson did you run the command in the root of the catalog? I'll have a look at this

Looks like its some new validation by Tekton.

image

Names now must be [valid DNS names](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names)

I'll add a `:` -> `.` conversion to the migration script.

**Pull request merged**
